<a href="https://colab.research.google.com/github/rsmaths29-note/Python_notes/blob/main/numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

why use numpy ?
1. numpy is faster in calculations.
2. numpy is written in C language. which is a low level language.
3. uses less memory.
4. vectorized operations.
5. contageious memory allocation.
6. builtin support for mathematical operations.

numpy datatypes :


1.   Boolean
2.   Signed Integers
3.   Unsigned Integers
4.   Floating Point
5.   Complex Numbers


In [ ]:
import numpy as np
import time as tm

in the following code, we first create two lists and then compute the set product XxY with the zip() fuction.

In [ ]:
X = list(range(100000000))
Y = list(range(100000000))
start = tm.time()
XxY = [i*j for i,j in zip(X,Y)]
end = tm.time()
print(end-start)

4.6644127368927


we do the same here but we use numpy arrays for the operations.

In [ ]:
import numpy as np
import time as tm

X = np.array(range(100000000))
Y = np.array(range(100000000))
start = tm.time()
XxY = X*Y
end = tm.time()
print(end-start)

0.15265679359436035


In [1]:
import numpy as np

In [ ]:
# empty array can be created as follows :
a = np.array([])

"""
arrays are homogeneous data types.
the following shows the datatype and the array itself.
the method a.dtype() will return int64 since the array contains integers
but if it had any other types of values, it would have implicitly done typecasting .

"""

a = np.array([1,2,3,4,5,6])
print(a, a.dtype)

[1 2 3 4 5 6] int64


In [17]:
"""
In NumPy, a.shape is a built-in attribute that returns a tuple of integers
representing the size of the array along each of its dimensions.
The length of the returned tuple corresponds to the total number of dimensions (a.ndim)

"""
# 1d array : a row vector : the shape is 5
a = np.array([1,2,3,4,5])
print(f"array shape of \n{a} =", a.shape, "\n")
print(f"array dimention of \n{a} =", a.ndim, "\n")

# 2d array : a 2 x 3 matrix :
a = np.array([
    [2,3,6],
    [3,5,7]
])
print(f"array shape of \n{a} =", a.shape, "\n")
print(f"array dimention of \n{a} =", a.ndim, "\n")


# 3d array : a 2 x 3 x 4 grid :
a = np.array([
    [
       [2,6,7],
       [3,5,0]
    ],
    [
        [4,9,0],
        [4,9,1]
    ],
    [
       [2,9,4],
       [8,3,6]
    ],
    [
        [3,0,2],
        [3,9,3]
    ]
])
print(f"array shape of \n{a} =", a.shape, "\n")
print(f"array dimention of \n{a} =", a.ndim, "\n")

"""
a.size returns the total number of elements contained within the array a.
It counts every single element across all rows, columns, and dimensions,
which is always equal to the mathematical product of the array's shape

"""
print(f"the size of our latest a is {a.size} "
       "that is the product of the shape tuple's elements" )

array shape of 
[1 2 3 4 5] = (5,) 

array dimention of 
[1 2 3 4 5] = 1 

array shape of 
[[2 3 6]
 [3 5 7]] = (2, 3) 

array dimention of 
[[2 3 6]
 [3 5 7]] = 2 

array shape of 
[[[2 6 7]
  [3 5 0]]

 [[4 9 0]
  [4 9 1]]

 [[2 9 4]
  [8 3 6]]

 [[3 0 2]
  [3 9 3]]] = (4, 2, 3) 

array dimention of 
[[[2 6 7]
  [3 5 0]]

 [[4 9 0]
  [4 9 1]]

 [[2 9 4]
  [8 3 6]]

 [[3 0 2]
  [3 9 3]]] = 3 

the size of our latest a is 24 that is the product of the shape tuple's elements


In [15]:
# the following creates a 3 x 3 matrix o zeros
a = np.zeros([3,3])
print(a)

# the following creates a 4 x 7 matrix of ones
a = np.ones([4,7])
print(a)

# the following creates a 5 x 9 matrix of some value a
a = np.full([5,9], "a")
print(a)

# the following creates an 7 x 7 identity matrix
a = np.eye(7)
print(a)

"""
np.arange() returns an ndarray of evenly spaced values within a specified mathematical interval.
It functions similarly to Python's native range() function, but instead of producing a range object,
it returns a high-performance NumPy array optimized for numerical operations

"""

# the following creates a range of values between 10 and 100 with  a step size of 5.
# its just like range() just faster ! so the ending value is not included.
# np.arange(starting, ending, step), the interval is [10,100)
a = np.arange(10,100,5)
print(a)

"""
The numpy.linspace() function returns an array of evenly spaced numbers over a specified mathematical interval.
Instead of defining the step size, you specify the total number of samples you want,
and NumPy automatically calculates the exact spacing

"""
# the following takes the interval [10, 100] and then divides it uniformly in 10 numbers
a = np.linspace(10,100,10)
print(a)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
